# Generated by Django 4.2.17 on 2025-01-27 15:23

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_organizationmember_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET', default='Asia/Shanghai'),
        ),
    ]
